baseurl = "/"
languageCode = "en-in"
title = "DataKind BLR"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Harnessing the power of data science in the service of humanity."
    footer = "&copy; [Data Kind BLR](https://t.co/EPquHzPd7N?amp=1) 2020 | [Github](https://github.com/DataKind-BLR) | [Twitter](https://twitter.com/DataKindBLR)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
